app:
  debug: false
  name: Xiaoxin RPA Pro
  version: 1.0.0
logging:
  console_enabled: true
  file_enabled: true
  level: INFO
mouse:
  click_delay: 0.1
  fail_safe: true
  move_duration: 0.5
templates:
  auto_resolution: true
  base_path: templates
  supported_formats:
  - .png
  - .jpg
  - .jpeg
  - .bmp
vision:
  confidence_threshold: 0.8
  grayscale: true
  match_method: cv2.TM_CCOEFF_NORMED
window:
  activate_timeout: 2.0
  search_timeout: 5.0
workflow:
  error_retry: 3
  screenshot_on_error: true
  step_delay: 0.5
