# 企业微信工作流策略配置

# 策略基本信息
strategy:
  name: "wxwork_semi_auto"
  description: "企业微信半自动化策略"
  version: "1.0.2"

# 窗口配置
window:
  # 窗口位置和大小配置
  position:
    x: 100
    y: 100
  size:
    width: 2019
    height: 1470
  # 是否启用自动调整
  auto_adjust: true

# 企业微信缓存清理配置
cache_cleaner:
  # 是否启用缓存清理
  enabled: true
  # 清理频率设置（循环次数）
  clean_interval: 1000  # 每1000次循环清理一次，即 index % 1000 == 0 时清理
  # 清理的缓存类型（空数组表示清理所有类型）
  clean_patterns: []  # 如：['avatar_cache', 'general_cache'] 或 [] 表示全部